version: '3'

services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    ports:
    - "3000:3000"
    volumes: 
      - .:/app
    command: /app/build/TodoMVC

  test:
    build: .
    volumes: 
      - .:/app
    environment: { TEST }
    command: make test

  bash:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    volumes: 
      - .:/app
    entrypoint: bash
