version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "sudo apt-get update && export DEBIAN_FRONTEND=noninteractive && sudo apt-get -y install --no-install-recommends clang-format clang-tidy clang-tools clang clangd libc++-dev libc++1 libc++abi-dev libc++abi1 libclang-dev libclang1 liblldb-dev libomp-dev libomp5 lld lldb llvm-dev llvm-runtime llvm python-clang libcurl4-openssl-dev libblocksruntime-dev libkqueue-dev libpthread-workqueue-dev git build-essential python cmake ninja-build systemtap-sdt-dev libbsd-dev linux-libc-dev apache2-utils fswatch uuid-dev"
      - run:
          name: "Build libdispatch"
          command: "git clone https://github.com/apple/swift-corelibs-libdispatch.git && cd swift-corelibs-libdispatch && cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ . && sudo ninja install && cd .. && rm -rf swift-corelibs-libdispatch"    
      - run:
          name: "Testing"
          command: "LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH PATH=/usr/local/lib:$PATH make test"

workflows:
  test-workflow:
    jobs:
      - test
