name: test
on: [push]
env:
  BUILD_ENV: test
  TEST_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/express-test?sslmode=disable

jobs:
  test-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:master
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: express-test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y postgresql-client libpq-dev
          curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
          chmod +x /usr/local/bin/dbmate
      - run: make lint
      - run: make test-leaks
      - run: make test
      - run: make test-analyze
      - run: make test-coverage-html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: build/code-coverage.html

  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install jansson libjwt libpq postgresql dbmate
      - name: Add PostgreSQL to PATH
        run: echo "/usr/local/opt/libpq/bin" >> $GITHUB_PATH
      - run: make test