name: test
on: [push]
env:
  BUILD_ENV: test
jobs:
  test-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/williamcotton/express-c:release
    steps:
      - uses: actions/checkout@v2
      - run: make lint
      - run: make test-leaks
      - run: make test
  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: ln -s "$(brew --prefix llvm)/bin/clang-tidy" "/usr/local/bin/clang-tidy"
      - run: make lint
      - run: make test-leaks
      - run: make test
