name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/williamcotton/express-c:release
    steps:
      - uses: actions/checkout@v2
      - run: make test-leaks
      - run: make test
